/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Talkgroup = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const NetworkType = IDL.Variant({
  'dmr' : IDL.Null,
  'p25' : IDL.Null,
  'ysf' : IDL.Null,
  'nxdn' : IDL.Null,
  'analog' : IDL.Null,
  'others' : IDL.Null,
  'dstar' : IDL.Null,
});
export const PersistentNetwork = IDL.Record({
  'networkLabel' : IDL.Text,
  'address' : IDL.Text,
  'talkgroups' : IDL.Vec(Talkgroup),
  'networkType' : NetworkType,
});
export const ImmutableUserProfile = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'licenseAcknowledgement' : IDL.Bool,
  'ssid' : IDL.Opt(IDL.Nat),
  'favoriteNetworks' : IDL.Vec(IDL.Text),
  'callsign' : IDL.Text,
  'dmrId' : IDL.Opt(IDL.Nat),
});
export const PersistentTransmission = IDL.Record({
  'fromCallsign' : IDL.Text,
  'talkgroup' : IDL.Text,
  'network' : IDL.Text,
  'dmrOperatorName' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'dmrId' : IDL.Opt(IDL.Nat),
  'dmrOperatorLocation' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const SignalMessage = IDL.Record({
  'roomKey' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBuiltinNetworks' : IDL.Func([], [IDL.Vec(PersistentNetwork)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(ImmutableUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoriteNetworks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getNowHearing' : IDL.Func([], [IDL.Vec(PersistentTransmission)], ['query']),
  'getSignalsAfterTimestampForRoom' : IDL.Func(
      [Time, IDL.Text],
      [IDL.Vec(SignalMessage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ImmutableUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([ImmutableUserProfile], [], []),
  'sendSignal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleFavoriteNetwork' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateNowHearing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Talkgroup = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const NetworkType = IDL.Variant({
    'dmr' : IDL.Null,
    'p25' : IDL.Null,
    'ysf' : IDL.Null,
    'nxdn' : IDL.Null,
    'analog' : IDL.Null,
    'others' : IDL.Null,
    'dstar' : IDL.Null,
  });
  const PersistentNetwork = IDL.Record({
    'networkLabel' : IDL.Text,
    'address' : IDL.Text,
    'talkgroups' : IDL.Vec(Talkgroup),
    'networkType' : NetworkType,
  });
  const ImmutableUserProfile = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'licenseAcknowledgement' : IDL.Bool,
    'ssid' : IDL.Opt(IDL.Nat),
    'favoriteNetworks' : IDL.Vec(IDL.Text),
    'callsign' : IDL.Text,
    'dmrId' : IDL.Opt(IDL.Nat),
  });
  const PersistentTransmission = IDL.Record({
    'fromCallsign' : IDL.Text,
    'talkgroup' : IDL.Text,
    'network' : IDL.Text,
    'dmrOperatorName' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'dmrId' : IDL.Opt(IDL.Nat),
    'dmrOperatorLocation' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const SignalMessage = IDL.Record({
    'roomKey' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBuiltinNetworks' : IDL.Func(
        [],
        [IDL.Vec(PersistentNetwork)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(ImmutableUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoriteNetworks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getNowHearing' : IDL.Func(
        [],
        [IDL.Vec(PersistentTransmission)],
        ['query'],
      ),
    'getSignalsAfterTimestampForRoom' : IDL.Func(
        [Time, IDL.Text],
        [IDL.Vec(SignalMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ImmutableUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([ImmutableUserProfile], [], []),
    'sendSignal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleFavoriteNetwork' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateNowHearing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };