/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ImmutableUserProfile {
  'name' : [] | [string],
  'licenseAcknowledgement' : boolean,
  'ssid' : [] | [bigint],
  'favoriteNetworks' : Array<string>,
  'callsign' : string,
  'dmrId' : [] | [bigint],
}
export type NetworkType = { 'dmr' : null } |
  { 'p25' : null } |
  { 'ysf' : null } |
  { 'nxdn' : null } |
  { 'analog' : null } |
  { 'others' : null } |
  { 'dstar' : null };
export interface PersistentNetwork {
  'networkLabel' : string,
  'address' : string,
  'talkgroups' : Array<Talkgroup>,
  'networkType' : NetworkType,
}
export interface PersistentTransmission {
  'fromCallsign' : string,
  'talkgroup' : string,
  'network' : string,
  'dmrOperatorName' : [] | [string],
  'timestamp' : bigint,
  'dmrId' : [] | [bigint],
  'dmrOperatorLocation' : [] | [string],
}
export interface SignalMessage {
  'roomKey' : string,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Talkgroup { 'id' : string, 'name' : string }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBuiltinNetworks' : ActorMethod<[], Array<PersistentNetwork>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ImmutableUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavoriteNetworks' : ActorMethod<[], Array<string>>,
  'getNowHearing' : ActorMethod<[], Array<PersistentTransmission>>,
  'getSignalsAfterTimestampForRoom' : ActorMethod<
    [Time, string],
    Array<SignalMessage>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [ImmutableUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[ImmutableUserProfile], undefined>,
  'sendSignal' : ActorMethod<[string, string], undefined>,
  'toggleFavoriteNetwork' : ActorMethod<[string], boolean>,
  'updateNowHearing' : ActorMethod<
    [string, string, string, [] | [bigint], [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];