/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PersistentNetwork {
    networkLabel: string;
    address: string;
    talkgroups: Array<Talkgroup>;
    networkType: NetworkType;
}
export type Time = bigint;
export interface PersistentTransmission {
    fromCallsign: string;
    talkgroup: string;
    network: string;
    dmrOperatorName?: string;
    timestamp: bigint;
    dmrId?: bigint;
    dmrOperatorLocation?: string;
}
export interface Talkgroup {
    id: string;
    name: string;
}
export interface SignalMessage {
    roomKey: string;
    content: string;
    sender: Principal;
    timestamp: Time;
}
export interface ImmutableUserProfile {
    name?: string;
    licenseAcknowledgement: boolean;
    ssid?: bigint;
    favoriteNetworks: Array<string>;
    callsign: string;
    dmrId?: bigint;
}
export enum NetworkType {
    dmr = "dmr",
    p25 = "p25",
    ysf = "ysf",
    nxdn = "nxdn",
    analog = "analog",
    others = "others",
    dstar = "dstar"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getBuiltinNetworks(): Promise<Array<PersistentNetwork>>;
    getCallerUserProfile(): Promise<ImmutableUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavoriteNetworks(): Promise<Array<string>>;
    getNowHearing(): Promise<Array<PersistentTransmission>>;
    getSignalsAfterTimestampForRoom(callerTimestamp: Time, roomKey: string): Promise<Array<SignalMessage>>;
    getUserProfile(profileOwner: Principal): Promise<ImmutableUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: ImmutableUserProfile): Promise<void>;
    sendSignal(content: string, roomKey: string): Promise<void>;
    toggleFavoriteNetwork(networkId: string): Promise<boolean>;
    updateNowHearing(fromCallsign: string, network: string, talkgroup: string, dmrId: bigint | null, dmrOperatorName: string | null, dmrOperatorLocation: string | null): Promise<void>;
}
import type { ImmutableUserProfile as _ImmutableUserProfile, NetworkType as _NetworkType, PersistentNetwork as _PersistentNetwork, PersistentTransmission as _PersistentTransmission, Talkgroup as _Talkgroup, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getBuiltinNetworks(): Promise<Array<PersistentNetwork>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuiltinNetworks();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuiltinNetworks();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<ImmutableUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavoriteNetworks(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoriteNetworks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoriteNetworks();
            return result;
        }
    }
    async getNowHearing(): Promise<Array<PersistentTransmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNowHearing();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNowHearing();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalsAfterTimestampForRoom(arg0: Time, arg1: string): Promise<Array<SignalMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalsAfterTimestampForRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalsAfterTimestampForRoom(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<ImmutableUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: ImmutableUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_ImmutableUserProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_ImmutableUserProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendSignal(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSignal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSignal(arg0, arg1);
            return result;
        }
    }
    async toggleFavoriteNetwork(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavoriteNetwork(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavoriteNetwork(arg0);
            return result;
        }
    }
    async updateNowHearing(arg0: string, arg1: string, arg2: string, arg3: bigint | null, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNowHearing(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNowHearing(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_ImmutableUserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableUserProfile): ImmutableUserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_NetworkType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NetworkType): NetworkType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentNetwork_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentNetwork): PersistentNetwork {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentTransmission_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentTransmission): PersistentTransmission {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImmutableUserProfile]): ImmutableUserProfile | null {
    return value.length === 0 ? null : from_candid_ImmutableUserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: [] | [string];
    licenseAcknowledgement: boolean;
    ssid: [] | [bigint];
    favoriteNetworks: Array<string>;
    callsign: string;
    dmrId: [] | [bigint];
}): {
    name?: string;
    licenseAcknowledgement: boolean;
    ssid?: bigint;
    favoriteNetworks: Array<string>;
    callsign: string;
    dmrId?: bigint;
} {
    return {
        name: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.name)),
        licenseAcknowledgement: value.licenseAcknowledgement,
        ssid: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.ssid)),
        favoriteNetworks: value.favoriteNetworks,
        callsign: value.callsign,
        dmrId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.dmrId))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fromCallsign: string;
    talkgroup: string;
    network: string;
    dmrOperatorName: [] | [string];
    timestamp: bigint;
    dmrId: [] | [bigint];
    dmrOperatorLocation: [] | [string];
}): {
    fromCallsign: string;
    talkgroup: string;
    network: string;
    dmrOperatorName?: string;
    timestamp: bigint;
    dmrId?: bigint;
    dmrOperatorLocation?: string;
} {
    return {
        fromCallsign: value.fromCallsign,
        talkgroup: value.talkgroup,
        network: value.network,
        dmrOperatorName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.dmrOperatorName)),
        timestamp: value.timestamp,
        dmrId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.dmrId)),
        dmrOperatorLocation: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.dmrOperatorLocation))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    networkLabel: string;
    address: string;
    talkgroups: Array<_Talkgroup>;
    networkType: _NetworkType;
}): {
    networkLabel: string;
    address: string;
    talkgroups: Array<Talkgroup>;
    networkType: NetworkType;
} {
    return {
        networkLabel: value.networkLabel,
        address: value.address,
        talkgroups: value.talkgroups,
        networkType: from_candid_NetworkType_n6(_uploadFile, _downloadFile, value.networkType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dmr: null;
} | {
    p25: null;
} | {
    ysf: null;
} | {
    nxdn: null;
} | {
    analog: null;
} | {
    others: null;
} | {
    dstar: null;
}): NetworkType {
    return "dmr" in value ? NetworkType.dmr : "p25" in value ? NetworkType.p25 : "ysf" in value ? NetworkType.ysf : "nxdn" in value ? NetworkType.nxdn : "analog" in value ? NetworkType.analog : "others" in value ? NetworkType.others : "dstar" in value ? NetworkType.dstar : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentTransmission>): Array<PersistentTransmission> {
    return value.map((x)=>from_candid_PersistentTransmission_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentNetwork>): Array<PersistentNetwork> {
    return value.map((x)=>from_candid_PersistentNetwork_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ImmutableUserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImmutableUserProfile): _ImmutableUserProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    licenseAcknowledgement: boolean;
    ssid?: bigint;
    favoriteNetworks: Array<string>;
    callsign: string;
    dmrId?: bigint;
}): {
    name: [] | [string];
    licenseAcknowledgement: boolean;
    ssid: [] | [bigint];
    favoriteNetworks: Array<string>;
    callsign: string;
    dmrId: [] | [bigint];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        licenseAcknowledgement: value.licenseAcknowledgement,
        ssid: value.ssid ? candid_some(value.ssid) : candid_none(),
        favoriteNetworks: value.favoriteNetworks,
        callsign: value.callsign,
        dmrId: value.dmrId ? candid_some(value.dmrId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
